name: health_buddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  # device_preview: ^1.2.0
  
  

  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  flutter_secure_storage: ^9.2.4

  provider: ^6.1.3
  shared_preferences: ^2.0.15
  android_alarm_manager_plus:
  permission_handler:
  intl: ^0.19.0
  table_calendar: ^3.1.0
  flutter_local_notifications: ^19.0.0
  geolocator: ^13.0.3
  google_maps_flutter: ^2.12.0
  url_launcher: ^6.2.4
  firebase_core: ^3.13.0
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.3
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.4
  cupertino_icons: ^1.0.8
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  sqflite:
  path_provider:
  flutter_background_service: ^5.1.0
  flutter_tts: ^4.2.2
  flutter_foreground_task: ^8.17.0
  font_awesome_flutter: ^10.8.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  flutter_animate: ^4.3.0
  flutter_screenutil: ^5.9.0
  video_player: ^2.9.5

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - images/photo2.png
    - images/photo3.png
    - images/drugs.png
    - images/logo.png
    - images/logo2.jpeg
    - images/syringe.png
    - images/user.png
    - assets/medicines.json
    - images/MedTrack -logo.png
    - images/MedTrack -name.png
    - images/MedTrack-icon.png
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/MedTrack-icon.png"

    
    #  - assets/sounds/notification_sound.mp3

    


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package